kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: cotkgi-vsphere-local
  annotations:
    storageclass.kubernetes.io/is-default-class: "true"
provisioner: kubernetes.io/vsphere-volume
reclaimPolicy: Retain
parameters:
  diskformat: zeroedthick
